<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://gras.webservice.ibs" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" name="graswebservice" targetNamespace="http://gras.webservice.ibs" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="https://www.centralbank.net.in:443/graswebservice?xsd=1" namespace="http://gras.webservice.ibs" />
    </xsd:schema>
  </types>
  <message name="verifyGRASData">
    <part name="parameters" element="tns:verifyGRASData" />
  </message>
  <message name="verifyGRASDataResponse">
    <part name="parameters" element="tns:verifyGRASDataResponse" />
  </message>
  <portType name="IBSGrasWebServiceImpl">
    <operation name="verifyGRASData">
      <input wsam:Action="http://gras.webservice.ibs/IBSGrasWebServiceImpl/verifyGRASDataRequest" message="tns:verifyGRASData" />
      <output wsam:Action="http://gras.webservice.ibs/IBSGrasWebServiceImpl/verifyGRASDataResponse" message="tns:verifyGRASDataResponse" />
    </operation>
  </portType>
  <binding name="graswebservicePortBinding" type="tns:IBSGrasWebServiceImpl">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="verifyGRASData">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="graswebservice">
    <port name="graswebservicePort" binding="tns:graswebservicePortBinding">
      <soap:address location="https://www.centralbank.net.in:443/graswebservice" />
    </port>
  </service>
</definitions>